### ISSUE TITLE
Add favorite Berkeley restaurant next to your name?

### ISSUE THREAD

**Issue by rrohit4** [joewadcan/FirstPullRequest#246]
Hi @Rol-E,

It would be nice to know each other's favorite restaurant in Berkeley. What do you think?

**Comment by Rol-E** [comment]
Hey Rohit, sounds good...I have made the changes to your version (thanks for the review and for merging); I'd like for you to make changes to my version as well.

**Comment by rrohit4** [comment]
We are all set. Closing this issue now.
