### ISSUE TITLE
Charizard trivia update and attempt to mark out charizard lovers

### ISSUE THREAD

**Issue by oscarleonard** [joewadcan/FirstPullRequest#251]
@PhaizerJ did you know that the Charizard was inspired by real life Pteranodons?

https://en.wikipedia.org/wiki/Pteranodon

I'm going to add #charizardlover to your Fork FYI 👍 🐉  🐲

**Comment by PhaizerJ** [comment]
@oscarleonard @joewadcan 

This is excellent. So happy that we can build awareness around this. 🐲
