### ISSUE TITLE
Looking for a partner as well!

### ISSUE THREAD

**Issue by MWalkerBerk** [joewadcan/FirstPullRequest#314]
My GitHub username is @MWalkerBerk.

**Comment by cabudoy** [comment]
Are you still free? I need a partner. I'm @cabudoy

**Comment by MWalkerBerk** [comment]
@joewadcan @henriquedc1 Any advice on how I should proceed here? I don't have a partner to finish this assignment.

**Comment by sethlareau** [comment]
@MWalkerBerk I'll be your partner if you still need one! Going to work on this today!

**Comment by sethlareau** [comment]
@MWalkerBerk I'm ready to go if you still need a partner.

**Comment by sethlareau** [comment]
@MWalkerBerk I created a pull request to your branch for review. Let me know when you've had a chance to review and feel free to make a change for my review. Cheers!

**Comment by MWalkerBerk** [comment]
@sethlareau I merged your request and sent a pull request back over to you. I'll close this issue once the request is closed.

**Comment by sethlareau** [comment]
@MWalkerBerk Thanks. I merged your request. Should be good to go!
